language: ruby
rvm:
- 2.1.1
addons:
  code_climate:
    repo_token: fff35cf0f51ddd439d180905854ac395b4cea5f405d939db94ffc1ee12000ccc
deploy:
  provider: rubygems
  api_key:
    secure: RmhXBe0PWr9DYTHK2JDllNMJNAtBl2vRM8dawmI95gNhD5dPMSIZpKDRpSkGJogM3SvY2q18UMKgV9mec9JR8psXHr46LEPzjiM3hjQ5yAqoMoQfKKFt6dBNFuwswG6gVdQYENg140Dh8PtxaMfC6wtm+JP+Qx2B9gif7DXwGLI=
  gem: racktables-vlanparse
  on:
    repo: iavael/racktables-vlanparse
    tags: true
    branch: master
