language: ruby
rvm:
- ruby-2.1.5
addons:
  code_climate:
    repo_token: fff35cf0f51ddd439d180905854ac395b4cea5f405d939db94ffc1ee12000ccc
deploy:
  provider: rubygems
  api_key:
    secure: LlKkFUWx6US7zb8pBveQHjQ5K20IKiQOulYQSMOaF7I//yYhRkTz17JgLak8Edk/ntcAP4+ewjqMmmXbGbQWHz/4OqejkSVNSglT5DevtVd1W2/LxDxXyvWazGsG7jbjJDgeRwitxixaiwswVOCobuHUZJlKP3DOLKcbfnlxAnk=
  gem: racktables-vlanparse
  on:
    tags: true
    repo: iavael/racktables-vlanparse
