language: ruby
rvm:
- "2.6"
deploy:
  provider: rubygems
  api_key:
    secure: LlKkFUWx6US7zb8pBveQHjQ5K20IKiQOulYQSMOaF7I//yYhRkTz17JgLak8Edk/ntcAP4+ewjqMmmXbGbQWHz/4OqejkSVNSglT5DevtVd1W2/LxDxXyvWazGsG7jbjJDgeRwitxixaiwswVOCobuHUZJlKP3DOLKcbfnlxAnk=
  gem: racktables-vlanparse
  on:
    tags: true
    repo: iavael/racktables-vlanparse
before_install:
  - gem update bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULTlanguage: go
